name: "Youtube Music Downloader"
version: "1.1.36"
slug: "yt_music_downloader"
description: "Search and download high-quality MP3s from YouTube (Official Artist Channels)."
url: "https://github.com/ArduRom/ha-music-downloader"
startup: application
init: false
ingress: true
ingress_port: 8099
panel_icon: "mdi:music-box-multiple"
panel_title: "Music Downloader"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  download_dir: "/media"
  format: "bestaudio/best"
schema:
  download_dir: str
  format: str
map:
  - share:rw
  - media:rw
