name: "Youtube Music Downloader"
version: "1.1.4"
slug: "yt_music_downloader"
description: "Search and download high-quality MP3s from YouTube (Official Artist Channels)."
url: "https://github.com/USER/music-downloader-repo"
startup: application
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  download_dir: "/share/downloads/Music"
  format: "bestaudio/best"
schema:
  download_dir: str
  format: str
ports:
  5000/tcp: 5000
map:
  - share:rw
